### ISSUE TITLE
requirements file

### ISSUE THREAD

**Issue by samueleruffino99** [google-deepmind/perception_test#10]
Hello! 

Could you please provide a requirement file for baselines? In case one do not want to run it on google colab, or at least how to extract it from colab :)

Thank you!

**Comment by yangyi02** [comment]
A little confused. What do you mean the requirement files for baselines? Do you mean something like demo.py?

**Comment by ptchallenge-workshop** [comment]
Hi, We are putting one together, I will add to the repo when finished. Thanks!

**Comment by samueleruffino99** [comment]
I made requirements.txt as follows:

opencv-python
imageio
MoviePy
pygame
git+https://github.com/votchallenge/vot-toolkit-python
tqdm
torch
numpy

**Comment by sgjheywa** [comment]
Hi,

Sorry it's not practical to have a requirements.txt that covers all of the baselines, can we instead suggest using something like [pipreqs](https://github.com/bndr/pipreqs)? This should be able to export the required libraries for any of the baselines.

Thanks!
