### ISSUE TITLE
perception_test dataset conversion in COCO format

### ISSUE THREAD

**Issue by samueleruffino99** [google-deepmind/perception_test#12]
Hello, I would like to test this dataset on different models for object tracking.
I would like to convert it in COCO (YTVIS) format, to avoid changing too many things and store it in a standard way.
I was wondering if the current format is compatible (or already in COCO  format)
Do you have any suggestions, or maybe have you already implement something?

Thank you!

**Comment by sgjheywa** [comment]
Hi,

Thanks for your interest in the dataset! Currently, it's not available in the COCO format and we don't have plans to convert it any time soon. Sorry for any inconvenience.

Best,
Joe

**Comment by samueleruffino99** [comment]
I am working on it, maybe I could share it once I am done :)
