### ISSUE TITLE
Incorrect link in ReadMe

### ISSUE THREAD

**Issue by JacobChalk** [google-deepmind/perception_test#13]
Hi!

The link for the labels underneath "Temporal Sound Localisation" - Split: Train is given as:
`https://storage.googleapis.com/dm-perception-test/zip_data/action_localisation_train_annotations.zip`

When I think it should be:
`https://storage.googleapis.com/dm-perception-test/zip_data/sound_localisation_train_annotations.zip`

Hope this helps!

**Comment by sgjheywa** [comment]
Great spot! Thank you very much :)
