### ISSUE TITLE
Timestamps seem to be annoated as microsecond, not milisecond

### ISSUE THREAD

**Issue by JaesungHuh** [google-deepmind/perception_test#14]
Hi!! Thank you for this wonderful dataset.

It seems like timestamps are annotated as microsecond if we look at the corresponding frame_ids. However, you've explained that timestamps are annotated as a milisecond in the readme.

Could you check this?

Like the example below:
```
{'metadata': {'split': 'train',
  'video_id': 'video_9431',
  'frame_rate': 30,
  'num_frames': 1051,
  'resolution': [1080, 1920],
  'audio_samples': 1680754,
  'audio_sample_rate': 48000,
  'is_cup_game': 0,
  'is_camera_moving': 1},
 'action_localisation': [{'id': 0,
   'label_id': 23,
   'label': 'Opening something',
   'parent_objects': [1, 0],
   'timestamps': [0, 2866667],
   'frame_ids': [0, 86]},
..........}
```

frame_id : 86 should correspond to 86 / 30 = 2.866667 second, which is 2866.667 milisecond.

If the timestamps are marked as microsecond, then it makes sense. (2.866667 = 2866667 microsecond)

Thank you.

**Comment by sgjheywa** [comment]
Thank you for raising! You are correct, the labels are in miliseconds. I have changed the readme to reflect the microsecond annotations.
