### ISSUE TITLE
Issue with link to Sound Localisation Validation Features

### ISSUE THREAD

**Issue by JacobChalk** [google-deepmind/perception_test#15]
Hi!

The features linked for the sound validation features is given as:
[https://storage.googleapis.com/dm-perception-test/zip_data/sound_localisation_valid_sound_features.zip](url)

When I think it's more aligned with the train features link i.e. "audio features" not sound features:

[https://storage.googleapis.com/dm-perception-test/zip_data/sound_localisation_valid_audio_features.zip](url)

Hope this helps! :)

**Comment by sgjheywa** [comment]
Thank you for letting us know about this! :) I've updated the readme to the correct link.
