### ISSUE TITLE
Writeups of Challenge Solutions

### ISSUE THREAD

**Issue by tyleryzhu** [google-deepmind/perception_test#17]
Hi! I was wondering if there was any public posting of the technical reports that each team submitted from the challenge. I know there is a recording from the ICCV 2023 Workshop, but having the reports would be much more helpful than the 3 minute overviews provided there. Thanks!

**Comment by sgjheywa** [comment]
Hi, thanks for your interest, the report links are available on our [challenge page](https://ptchallenge-workshop.github.io/).
