### ISSUE TITLE
Cut frame for the training set

### ISSUE THREAD

**Issue by ZitianTang** [google-deepmind/perception_test#20]
Hi! I found your dataset really useful. I'm wondering if you have cut frame ids for the training videos. Just like `cut_frame_mapping_valid.json` but for the training set.

**Comment by ptchallenge-workshop** [comment]
Sorry for the delay, please find the link for the training split cut frames here: https://storage.googleapis.com/dm-perception-test/misc/cut_frame_mapping_train.json Thanks!

**Comment by ZitianTang** [comment]
Thank you!
