### ISSUE TITLE
Perception Test Challenge 2024 - Task 3 - Action Localisation

### ISSUE THREAD

**Issue by rixejzvdl649** [google-deepmind/perception_test#22]
![image](https://github.com/google-deepmind/perception_test/assets/142862250/e2e5c665-2b63-4aca-ba86-84347c7a2f37)

**Comment by rixejzvdl649** [comment]
No results to show.

**Comment by rixejzvdl649** [comment]
Is there some problem with this? score is not in dict form？

    example_submission = {'video_1009' :{'action_localisation':[
        {'label_id': 0, 'timestamp': [0.12, 0.34], score=0.293},
        {'label_id': 45, 'timestamp': [0.45, 0.65], score=0.652}]}}
        
        
        Is there some problem with this? score is not in dict form

**Comment by rixejzvdl649** [comment]
![image](https://github.com/google-deepmind/perception_test/assets/142862250/634dd7ec-52be-4ced-a292-795ee6d63633)

**Comment by ptchallenge-workshop** [comment]
Hey sorry, I am looking into this, we are having issues providing the relevant error messages through the server, can you contact me at heywardj@google.com with your submission IDs and I will provide more detailed information on errors. Thanks!
